services:
  backend:
    build: .

    ports:
      - '4000:4000'

    volumes:
      - .:/app

      - /app/node_modules

    env_file:
      - .env

    depends_on:
      - redis

  worker:
    build: .
    command: npm run worker
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:7-jammy

    ports:
      - '27017:27017'

    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine

    ports:
      - '6379:6379'

volumes:
  mongo_data:
